# Generated by Django 5.0.6 on 2024-07-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_alter_subscriptionprice_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionprice',
            name='features',
            field=models.TextField(blank=True, help_text='features for pricing, separated by new line', null=True),
        ),
    ]
