# Generated by Django 5.0.6 on 2024-07-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0016_remove_subscriptionprice_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subtitle',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionprice',
            name='interval',
            field=models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly')], default='month', max_length=120),
        ),
    ]
